// <auto-generated />
using System;
using Cmb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cmb.Database.Migrations
{
    [DbContext(typeof(DbCoffeeMachineContext))]
    [Migration("20240502132930_AddAmountToCoffeeRecipeIngredient")]
    partial class AddAmountToCoffeeRecipeIngredient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cmb.Database.Entities.DbCoffeeRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreateDate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoffeeRecipes");
                });

            modelBuilder.Entity("Cmb.Database.Entities.DbCoffeeRecipeIngredient", b =>
                {
                    b.Property<Guid>("CoffeeRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoffeeRecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CoffeeRecipeIngredients");
                });

            modelBuilder.Entity("Cmb.Database.Entities.DbIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreateDate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeleteDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Cmb.Database.Entities.DbCoffeeRecipeIngredient", b =>
                {
                    b.HasOne("Cmb.Database.Entities.DbCoffeeRecipe", "CoffeeRecipe")
                        .WithMany()
                        .HasForeignKey("CoffeeRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cmb.Database.Entities.DbIngredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeRecipe");

                    b.Navigation("Ingredient");
                });
#pragma warning restore 612, 618
        }
    }
}
